language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-lowest --prefer-stable --prefer-dist --no-interaction
  - if [[ $TRAVIS_PHP_VERSION == "7.4" ]]; then composer update phpunit/phpunit; fi
script:
  - make test
  - if [[ $TRAVIS_PHP_VERSION == "7.3" || $TRAVIS_PHP_VERSION == "7.4" ]]; then true; else make check-style; fi
